### ISSUE TITLE
cumulative time limit 中文？

### ISSUE THREAD

**Issue by richar983** [hanwu85/WCA-TC-2023_Open#15]
cumulative time limit 的中文翻譯？

現行中文版規則全部都是翻譯為「總時間限制」，但我認為因為近期規則的版本中可以出現並存的情況，其相對的部分為「時間限制」，或許是否將「總時間限制」 => 改動為 「累積時間限制」會更好呢？

不過這可能也會是一個為數不小的修改，「時間限制」於中英文版的規則與指導方針中，都各出現了約25次左右。但使用邏輯應該不會太複雜...

因為在 #11 中的 A1a+ 中，變得好像有一點點饒口的感覺？儘管我們知道實際運作的情況下閱讀不成問題...

在 英文版規則中，於 A1a 中明確的敘述了兩種time limit
`A1a) The organization team must apply at least one kind of time limit (time limit per attempt and/or cumulative time limit) to each round.`

中文版則是這樣 (感覺不是寫出兩種的名稱，而是敘述說明其差異？)
`A1a) 主辦團隊必須對每一輪做出時間限制（各次還原時間或每一輪時間總和）。`

應該有以下三種使用情境(?)：
Time Limit : 時間限制
time limit per attempt：單次時間限制
cumulative time limit：總時間限制 / 累積時間限制

分別是指 時間限制 這件事情、第一種時間限制 (單次時間限制)、第二種時間限制 (總時間限制)

現行尚未更新的中文版本，僅在  "規則" 中出現 7次 「總時間限制」；"方針" 中未出現
統計：
  英文版 「cumulative time limit」：規則 出現8次；方針 出現6次
  中文版 「總時間限制」：規則 出現7次；方針 出現0次

**Comment by hanwu85** [comment]
同意  這個也應該修正一下

**Comment by richar983** [comment]
這個改動，我傾向於如果可以的話在這次第一波正式上線的時候就一併更新上去！

因為這一個版本的規則將會強調 兩種時間限制可以同時並存，此時待中文版上線後，可能會很快的有多個窗口會開始對外宣傳規則變更的部分，此時如果可以已經統一好此處的翻譯方式可能會更加適當？


/// 雖然  solve 跟 attempt 的 解方塊 跟 還原 我也覺得應該要有更好的說法，但是那牽涉幅度太大可能不用急著這一波就動作。

**Comment by hanwu85** [comment]
我的cumulative time limit 翻譯提議

`總時間限制 `

`累積時間限制`

`時間累積限制`
`時間累積式限制`
`時間累積制限制`

`多次還原總時間限制`

**Comment by richar983** [comment]
如果就這些選項來說，我個人是更偏好 `累積時間限制` 的 .. 

因為 `總時間限制` 會跟既有單純提到 `time limit` `時間限制` 有點難以區別...


在規則 A1a  A1a1  A1a+ 中 也出現了 `time limit per attempt`
我想 `time limit per attempt` 應該也需要一併列入考慮...  例如 `單次時間限制`


所以我想三個相關聯的翻譯應該我會傾向於這樣，不知道吳翰大大怎麼看

Time Limit : 時間限制
time limit per attempt：單次時間限制
cumulative time limit：累積時間限制

**Comment by hanwu85** [comment]
我也同意如下

Time Limit : 時間限制
time limit per attempt：單次時間限制
cumulative time limit：累積時間限制

我先來弄PR
