### ISSUE TITLE
後續修正(紀錄清單)

### ISSUE THREAD

**Issue by richar983** [hanwu85/WCA-TC-2023_Open#45]
本處用於筆記完整閱讀時，發現可能值得討論修正的語句變化？ 
  ( 包含大量 非 本次規則修改的部分 ... )

### 優先順序：
- [x] 4b2++：`桌子四週` -> `桌子四周`  (錯字)

###  普通順序：
- [x] 1h1+：語句調整？
- [x] 1h1++：語句調整？
- [x] 2d+： `格外保密` -> `嚴格保密` ？
- [x] 3k2+：？
- [x] 3k2b+：語句修正？
- [x] 3k2b++：前兩句修正？
- [x] 3l1+：認知確認？ 單色塊都被視為中心塊，因此Logo不一定要貼在正中心？
- [x] 4b1+：語句結構修正？
- [x] 4b2++：應該要改用頓號？
- [x] 4f++：時時？
- [x] 9f5+：翻譯註解？！
- [x] 10f+：？
- [x] A2d1+：翻譯註解？
- [x] E2c2+：句子值得重翻。

**Comment by hanwu85** [comment]
`3l1+：認知確認？ 單色塊都被視為中心塊，因此Logo不一定要貼在正中心？
`
對，例如5x5方塊中間 3x3單色的部分 視為中心塊，我都差點忘了這個冷知識

**Comment by hanwu85** [comment]
9f5+，A2d1+的 翻譯註解是 多一步釐清 (英文版不夠清晰，所以中文版only)

**Comment by hanwu85** [comment]
修改內容在 #47
