### ISSUE TITLE
顆跟個

### ISSUE THREAD

**Issue by hanwu85** [hanwu85/WCA-TC-2023_Open#6]
有顆 也有 個
需統一

**Comment by richar983** [comment]
為認為需要提及幾個例句，以及前後文的匹配，再來分析應該要用哪一個比較好！

**Comment by richar983** [comment]
簡單的常識搜尋：「顆方塊」、「個方塊」

發現，「個方塊」總共只有出現3次，分別是

1.  9f12c > ... 原完成1個方塊，則成績 ...
2. 10d) 一個方塊的所有 ...
3. A2c1 > ... 罩住整個方塊，讓參賽者或 ...

我想這個issue應該是要探討，方塊的單位量詞(?)應該要用什麼。
我認為上述這三個使用「個」的Case，如果轉換成「顆」好像也沒有什麼問題，那或許統一使用「顆方塊」會更好一些？

「個方塊」 規則出現 3次；方針出現 0次
「顆方塊」 規則出現 11次；方針出現 6次

**Comment by hanwu85** [comment]
OK 同意 那三個改成顆

**Comment by richar983** [comment]
這個部分應該待修正上清單對吧？應該是等現在的PR都先推出去之後再進行？

**Comment by hanwu85** [comment]
對 merge 之後再統一修正

**Comment by hanwu85** [comment]
#34
